# Generated by Django 4.1 on 2022-08-25 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('account_number', models.IntegerField()),
                ('account_type', models.CharField(blank=True, default=False, max_length=30)),
                ('savings', models.IntegerField(default=False)),
                ('destination', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(default=False)),
                ('card_name', models.CharField(blank=True, max_length=30)),
                ('card_type', models.CharField(blank=True, default=False, max_length=30)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('security_code', models.IntegerField(default=False)),
                ('date_ofissue', models.DateTimeField(default=datetime.datetime.now)),
                ('account', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('Gender', models.CharField(max_length=1, null=True)),
                ('address', models.TextField()),
                ('age', models.PositiveSmallIntegerField(default=False)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('nationality', models.CharField(max_length=10, null=True)),
                ('phonenumber', models.CharField(max_length=15, null=True)),
                ('marital_status', models.CharField(max_length=30, null=True)),
                ('signature', models.ImageField(default=False, upload_to='')),
                ('employment_status', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(default=False, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(blank=True, default=False, max_length=30)),
                ('amount', models.IntegerField(default=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('loan_terms', models.CharField(blank=True, max_length=20)),
                ('payment_due_date', models.DateTimeField(default=datetime.datetime.now)),
                ('guaranter', models.CharField(blank=True, max_length=20)),
                ('balance', models.IntegerField(default=False)),
                ('duration', models.CharField(max_length=30, null=True)),
                ('interest_rate', models.IntegerField(default=False)),
                ('loan_status', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=50)),
                ('date_created', models.DateField(default=datetime.datetime.now)),
                ('recipient', models.CharField(blank=True, max_length=20)),
                ('notification_status', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(default=False, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('transaction', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('balance', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('pin', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('wallet_type', models.CharField(blank=True, max_length=30)),
                ('Customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_charge', models.IntegerField(default=False)),
                ('transaction_code', models.CharField(blank=True, default=False, max_length=30)),
                ('transaction_amount', models.IntegerField(default=False)),
                ('transaction_type', models.CharField(blank=True, default=False, max_length=30)),
                ('transaction_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('status_T', models.CharField(blank=True, max_length=20)),
                ('receipt', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_receipt', to='wallet.customer')),
                ('wallet', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Third_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('id_number', models.CharField(max_length=30)),
                ('status_third', models.CharField(default=False, max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('trasaction_cost', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Third_party_account', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('transaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reward_Transaction', to='wallet.transaction')),
            ],
        ),
    ]
